# Generated by Django 3.1.7 on 2021-03-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_count', models.IntegerField()),
                ('homepage', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('default_language', models.CharField(max_length=50)),
            ],
        ),
    ]
